[package]
name = "zero-alloc-lob"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"
llt-rs = { version = "0.4.2", features = ["arena_allocator"] }


[[bench]]
name = "latency"
harness = false